<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\irs;

class DummyIrsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $irs = [
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'E103',
        //         'sks' => 3,
        //         'kodemk' => 'PAIK6102',
        //         'hari' => 'Senin',
        //         'jam_mulai' => '07:00:00',
        //         'jam_selesai' => '09:30:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
        //         'pengampu_2' => 'Khadijah, S.Kom., M.Cs.',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'Lapangan Stadion UNDIP Tembalang',
        //         'sks' => 1,
        //         'kodemk' => 'UUW00005',
        //         'hari' => 'Rabu',
        //         'jam_mulai' => '06:00:00',
        //         'jam_selesai' => '06:50:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Dra. Endang Kumaidah, M.Kes.',
        //         'pengampu_2' => '',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'A303',
        //         'sks' => 3,
        //         'kodemk' => 'PAIK6104',
        //         'hari' => 'Rabu',
        //         'jam_mulai' => '09:40:00',
        //         'jam_selesai' => '12:10:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Dr. Sutikno, S.T., M.Cs.',
        //         'pengampu_2' => 'Dr. Aris Sugiharto, S.Si., M.Kom.',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'E102',
        //         'sks' => 3,
        //         'kodemk' => 'PAIK6103',
        //         'hari' => 'Rabu',
        //         'jam_mulai' => '13:00:00',
        //         'jam_selesai' => '15:30:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Rismiyati, B.Eng., M.Cs.',
        //         'pengampu_2' => 'Muhammad Malik Hakim, S.T., M.T.I.',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'E101',
        //         'sks' => 2,
        //         'kodemk' => 'UUW00007',
        //         'hari' => 'Kamis',
        //         'jam_mulai' => '07:00:00',
        //         'jam_selesai' => '08:40:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Dra. R.A.J. Atrinawati, M.Hum.',
        //         'pengampu_2' => '',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'B201',
        //         'sks' => 2,
        //         'kodemk' => 'PAIK6101',
        //         'hari' => 'Jumat',
        //         'jam_mulai' => '07:00:00',
        //         'jam_selesai' => '08:40:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Prof. Dr. Dra. Sunarsih, M.Si.',
        //         'pengampu_2' => 'Solikhin, S.Si., M.Sc.',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'B201',
        //         'sks' => 4,
        //         'kodemk' => 'PAIK6105',
        //         'hari' => 'Jumat',
        //         'jam_mulai' => '13:00:00',
        //         'jam_selesai' => '14:40:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Nurdin Bahtiar, S.Si., M.T.',
        //         'pengampu_2' => 'Sandy Kurniawan, S.Kom., M.Kom.',
        //         'pengampu_3' => 'Dr. Aris Sugiharto, S.Si., M.Kom.',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        //     [
        //         'nim' => '24060121130076',
        //         'ruang' => 'B103',
        //         'sks' => 3,
        //         'kodemk' => 'UUW00003',
        //         'hari' => 'Sabtu',
        //         'jam_mulai' => '07:00:00',
        //         'jam_selesai' => '09:30:00',
        //         'kelas' => 'A',
        //         'semester' => '4',
        //         'tahun_ajaran' => '2023/2024 Genap',
        //         'jurusan' => 'Informatika',
        //         'pengampu_1' => 'Dr. Drs. Slamet Subekti, M.Hum.',
        //         'pengampu_2' => '',
        //         'pengampu_3' => '',
        //         'status_irs' => 'Sudah Disetujui',
        //         'status_mk' => 'Baru',
        //     ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 4,
        //     'kodemk' => 'PAIK6202',
        //     'hari' => 'Senin',
        //     'jam_mulai' => '07:00:00',
        //     'jam_selesai' => '08:40:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Dr. Aris Puji Widodo, S.Si., M.T.',
        //     'pengampu_2' => 'Drs. Eko Adi Sarwoko, M.Komp.',
        //     'pengampu_3' => '',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 2,
        //     'kodemk' => 'UUW00004',
        //     'hari' => 'Senin',
        //     'jam_mulai' => '08:50:00',
        //     'jam_selesai' => '10:30:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Dr. Drs. Muh Abdullah, M.A.',
        //     'pengampu_2' => '',
        //     'pengampu_3' => '',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 2,
        //     'kodemk' => 'UUW00006',
        //     'hari' => 'Senin',
        //     'jam_mulai' => '15:40:00',
        //     'jam_selesai' => '17:20:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Priyo Sidik Sasongko, S.Si., M.Kom.',
        //     'pengampu_2' => 'Guruh Aryotejo, S.Kom., M.Sc.',
        //     'pengampu_3' => 'Nurdin Bahtiar, S.Si., M.T.',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 3,
        //     'kodemk' => 'PAIK6204',
        //     'hari' => 'Selasa',
        //     'jam_mulai' => '07:00:00',
        //     'jam_selesai' => '09:30:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Dr. Retno Kusumaningrum, S.Si., M.Kom.',
        //     'pengampu_2' => 'Priyo Sidik Sasongko, S.Si., M.Kom.',
        //     'pengampu_3' => 'Dr. Aris Sugiharto, S.Si., M.Kom.',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 3,
        //     'kodemk' => 'PAIK6203',
        //     'hari' => 'Selasa',
        //     'jam_mulai' => '13:00:00',
        //     'jam_selesai' => '15:30:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Rismiyati, B.Eng., M.Cs.',
        //     'pengampu_2' => 'Muhammad Malik Hakim, S.T., M.T.I.',
        //     'pengampu_3' => '',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 2,
        //     'kodemk' => 'UUW00011',
        //     'hari' => 'Rabu',
        //     'jam_mulai' => '08:50:00',
        //     'jam_selesai' => '10:30:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Suparno, S.Ag., M.Si.',
        //     'pengampu_2' => '',
        //     'pengampu_3' => '',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'K102',
        //     'sks' => 3,
        //     'kodemk' => 'PAIK6603',
        //     'hari' => 'Rabu',
        //     'jam_mulai' => '13:00:00',
        //     'jam_selesai' => '15:30:00',
        //     'kelas' => 'B',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Yunila Dwi Putri Ariyanti, S.Kom., M.Kom.',
        //     'pengampu_2' => 'Nurdin Bahtiar, S.Si., M.T.',
        //     'pengampu_3' => 'Khadijah, S.Kom., M.Cs.',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        // [
        //     'nim' => '24060121130076',
        //     'ruang' => 'E102',
        //     'sks' => 2,
        //     'kodemk' => 'PAIK6201',
        //     'hari' => 'Kamis',
        //     'jam_mulai' => '07:00:00',
        //     'jam_selesai' => '08:40:00',
        //     'kelas' => 'A',
        //     'semester' => '4',
        //     'tahun_ajaran' => '2023/2024 Genap',
        //     'jurusan' => 'Informatika',
        //     'pengampu_1' => 'Solikhin, S.Si., M.Sc.',
        //     'pengampu_2' => 'Farikhin, S.Si., M.Si., Ph.D.',
        //     'pengampu_3' => '',
        //     'status_irs' => 'Sudah Disetujui',
        //     'status_mk' => 'Baru',
        // ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E103',
            'sks' => 4,
            'kodemk' => 'PAIK6301',
            'hari' => 'Senin',
            'jam_mulai' => '07:00:00',
            'jam_selesai' => '08:40:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Edy Suharto, S.T., M.Kom.',
            'pengampu_2' => 'Sandy Kurniawan, S.Kom., M.Kom.',
            'pengampu_3' => '',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E101',
            'sks' => 2,
            'kodemk' => 'PAIK6306',
            'hari' => 'Senin',
            'jam_mulai' => '10:40:00',
            'jam_selesai' => '12:20:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Dr. Dra. Tatik Widiharih, M.Si.',
            'pengampu_2' => 'Dr. Yeva Fadhilah Ashari, S.Si., M.Si.',
            'pengampu_3' => 'Sugito, S.Si., M.Si.',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E103',
            'sks' => 4,
            'kodemk' => 'PAIK6303',
            'hari' => 'Senin',
            'jam_mulai' => '13:00:00',
            'jam_selesai' => '14:40:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Beta Noranita, S.Si., M.Kom.',
            'pengampu_2' => 'Satriyo Adhy, S.Si., M.T.',
            'pengampu_3' => '',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E102',
            'sks' => 3,
            'kodemk' => 'PAIK6506',
            'hari' => 'Senin',
            'jam_mulai' => '15:40:00',
            'jam_selesai' => '18:10:00',
            'kelas' => 'C',
            'semester' => '5',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Edy Suharto, S.T., M.Kom.',
            'pengampu_2' => 'Prajanto Wahyu Adi, M.Kom.',
            'pengampu_3' => 'Yunila Dwi Putri Ariyanti, S.Kom., M.Kom.',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E103',
            'sks' => 3,
            'kodemk' => 'PAIK6304',
            'hari' => 'Selasa',
            'jam_mulai' => '07:00:00',
            'jam_selesai' => '09:30:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Priyo Sidik Sasongko, S.Si., M.Kom.',
            'pengampu_2' => 'Dr. Indra Waspada, S.T., M.T.I.',
            'pengampu_3' => 'Etna Vianita, S.Mat., M.Mat.',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E103',
            'sks' => 3,
            'kodemk' => 'PAIK6302',
            'hari' => 'Selasa',
            'jam_mulai' => '09:40:00',
            'jam_selesai' => '12:10:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Guruh Aryotejo, S.Kom., M.Sc.',
            'pengampu_2' => 'Drs. Eko Adi Sarwoko, M.Komp.',
            'pengampu_3' => '',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'K202',
            'sks' => 3,
            'kodemk' => 'PAIK6305',
            'hari' => 'Kamis',
            'jam_mulai' => '15:40:00',
            'jam_selesai' => '18:10:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Drs. Eko Adi Sarwoko, M.Komp.',
            'pengampu_2' => 'Dinar Mutiara Kusumo Nugraheni, S.T., M.InfoTech.(Comp.), Ph.D.',
            'pengampu_3' => '',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        [
            'nim' => '24060121130076',
            'ruang' => 'E102',
            'sks' => 2,
            'kodemk' => 'UUW00008',
            'hari' => 'Jumat',
            'jam_mulai' => '07:00:00',
            'jam_selesai' => '08:40:00',
            'kelas' => 'A',
            'semester' => '3',
            'tahun_ajaran' => '2023/2024 Genap',
            'jurusan' => 'Informatika',
            'pengampu_1' => 'Prajanto Wahyu Adi, M.Kom.',
            'pengampu_2' => 'Satriyo Adhy, S.Si., M.T.',
            'pengampu_3' => 'Dr. Aris Puji Widodo, S.Si., M.T.',
            'status_irs' => 'Sudah Disetujui',
            'status_mk' => 'Baru',
        ],
        ];
        foreach($irs as $key => $val){
            irs::create($val);
        }
    }
}